meta_product_name: "Kenko"
meta_title: "Kenko app - Votre carnet de santé dans la poche"
meta_description: "Kenko est votre dossier nouveau médical nomade."
meta_image: "prescription.png"                       # should exist in `app/assets/images/`
twitter_account: "@appkenko"   # required for Twitter Cards
